# Generated by Django 5.1.3 on 2025-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
